16 add further descriptions about model parameters in documentation
USEPA/CompTox-ToxCast-tcplFit2 pull request #45
Opened 2023-09-18 20:05 UTC by gracezhihuizhao

[Available Curves in tcplfit2.pdf](https://github.com/USEPA/CompTox-ToxCast-tcplFit2/files/12652787/Available.Curves.in.tcplfit2.pdf)

After discussion with SME's, creating a vignette that contains the parameter descriptions and plots that shows how curve shape changes as parameter values change. Included rendered pdf for easy review.

2023-09-19 14:29 UTC, sedavid01 requested changes
Provided some comments to get you started on polishing this vignette.  Remember that you are developing documentation to help users of many levels from brand new users and newcomers to dose-response modeling, to 'wet-lab' individuals, and experienced scientists/modelers.  Provide enough information to explain what is going on but concise enough that it is not burdensome.

This is a good start, just continue building and polishing the vignette you have here.

2023-09-19 14:29 UTC, sedavid01 commented on vignettes/curve-shapes.Rmd
> +#exp3_plot1
Question... Is there a reason that these plot objects are commented out?

2023-09-19 14:29 UTC, sedavid01 commented on vignettes/curve-shapes.Rmd
Use grid to show related figures side-by-side. Make sure to add captions to figures as well.

2023-09-19 14:29 UTC, sedavid01 commented on vignettes/curve-shapes.Rmd
Suggest adding brief comments to the code chunks.

2023-09-22 13:00 UTC, sedavid01 requested changes
The updates are looking good so far.  Especially the section linking.  However, there is still quite a bit of polishing that can be done to improve the quality of the vignette.  Please review the suggestions and adjust accordingly.

Please reach out with any questions or clarifications that are necessary.

2023-09-26 21:07 UTC, sedavid01 requested changes
Great improvements!  Please continue polishing up - there are some pointed suggestion in the comments here.

2023-09-26 21:07 UTC, sedavid01 commented on vignettes/curve-shapes.Rmd
Suggest making sure the legend matches the order (from top to bottom) the color of the respective curve shapes. See "a" plot for Figure 6.

2023-09-28 13:57 UTC, gracezhihuizhao commented
> Great improvements! Please continue polishing up - there are some pointed suggestion in the comments here.
@sedavid01 I made some changes to the plots and fixed some typos.. it's ready for review

2023-09-29 14:50 UTC, sedavid01 approved these changes
Made some minor changes, but overall looks good from my end.  Approving.
Please wait to merge until there is input from SME's that use the package.

2024-05-09 18:19 UTC, sedavid01 commented
This PR has been approved and outstanding for a while.  I assume SME's have no further comments at this time.  Thus, merging into "dev".  Further refinements may be requested and  scoped in later issues.

2024-05-09 18:19 UTC, merged