44 add the rmd for conducting unit tests and polishing for future developers
USEPA/CompTox-ToxCast-tcplFit2 pull request #47
Opened 2023-09-20 19:57 UTC by gracezhihuizhao

2023-09-27 14:41 UTC, sedavid01 requested changes
Minor comments to resolve.

2023-09-27 14:41 UTC, sedavid01 commented on analyses/unit test demo.Rmd
Suggest splitting the vignette into sections to make it easier to navigate.

2023-09-27 14:41 UTC, sedavid01 commented on analyses/unit test demo.Rmd
> +```{r}
Please make this chunk scrollable, and in the text above I would mention which 'code section' the hard coding occurs (i.e. "Optimize the model").

2023-09-27 14:41 UTC, sedavid01 commented on analyses/unit test demo.Rmd
> +Run the the test again, but this time it will fail because a bug was introduced by the new changes. The output will show you what the code returned v.s. what it expect.
Minor update: "returned versus what is expected."

2023-09-27 21:01 UTC, gracezhihuizhao commented
> Minor comments to resolve.

@sedavid01 changes made, ready for review

2023-09-28 13:46 UTC, sedavid01 approved these changes

2023-09-28 15:02 UTC, merged