25 add captions to the tcplfit2 vignette figures
USEPA/CompTox-ToxCast-tcplFit2 pull request #65
Opened 2023-10-19 19:47 UTC by gracezhihuizhao

2023-12-11 14:06 UTC, sedavid01 requested changes
Overall the figure captions look good.  There are some suggestions for polishing up the language for clarity and conciseness.  Also, suggest reading through each figure caption after making suggested updates to ensure there are no typos or grammatical errors, and the description still flows well.  If there are any issues feel free to edit as necessary to make sure the figure caption is well polished.

Thank you again for your hard work on updating these!

2023-12-11 14:06 UTC, sedavid01 commented on vignettes/tcplfit2-vignette.Rmd
> +**Figure 7**: This plot shows the BMD and confidence interval before and after "censoring". The green line and green "X" mark the BMD before "censoring" and the green column represents the confidence
Suggest looking at the comments for Figure 6 as many of those may apply here.

2023-12-11 18:30 UTC, gracezhihuizhao commented on vignettes/tcplfit2-vignette.Rmd
> +
@sedavid01 Sentence 5 - concRespPlot dose not have a "X" marker for BMD only a vertical line. It's something I added for figures in example 5.

2023-12-13 19:37 UTC, sedavid01 requested changes
Overall the updates are looking good thus far.  There are still some outstanding issues that need to be addressed.  Please see the comments from this review and feel free to reach out if you have any questions/comments.

2023-12-13 19:37 UTC, sedavid01 commented on vignettes/tcplfit2-vignette.Rmd
> +
Suggested rewording:
"This figure provides an example of plots generated using the `tcplfit2` ... Each plot displays all model fits for one row of data in the `signatures` dataset."
(Sorry for the additional rewording... Just read through the caption and it still seemed slightly off.  Feel free to re-read after this update and make any additional tweaks.)

2023-12-13 19:37 UTC, sedavid01 commented on vignettes/tcplfit2-vignette.Rmd
> +**Figure 4:** These figures are plots generated from using one of the plotting option in `tcplfit2`: using the `concRespPlot` function. `concRespPlot`, when takes output from `concRespCore`, plots th
See suggestion for the Figure 3 caption.

2023-12-13 19:37 UTC, sedavid01 commented on vignettes/tcplfit2-vignette.Rmd
> +**Figure 7**: This plot shows the estimated BMD and confidence interval before and after "censoring". The green line and the "X" mark the BMD before "censoring" along with the green shaed region repr
Typo sentence 2 "shaed" should be "shaded".

2023-12-14 20:41 UTC, sedavid01 approved these changes
Reviewed and polished figure captions in the tcplfit2 vignette.  Marking this PR as approved and it is ready to be merged into 'dev'.

2023-12-14 20:42 UTC, merged

2023-12-14 20:42 UTC, sedavid01 commented
@brown-jason, changes are merged to 'master' please verify when you get the chance and if any branch clean-up is needed please either do so or provide guidance/instructions. Thanks, -Sarah