83 errfun should default to dt4 if not provided to tcplhit2 core
USEPA/CompTox-ToxCast-tcplFit2 pull request #84
Opened 2024-02-28 15:01 UTC by gracezhihuizhao

'errfun' is required in `tcplhit2_core`. Adding a check for if this parameter is provided in `params` / output from `tcplfit2_core`. If the function should throw an error.

2024-02-28 15:19 UTC, sedavid01 reviewed
@gracezhihuizhao - Update looks good to me.  Just one minor suggestion provided.

@brown-jason:
* Once this update is done may want to have @cthunes test this update fixes the previous issue - unless it is deemed unnecessary from your end.
* Please notify if you think we should add a unit test to tcplfit2 for this edge case.

Thanks, 
-Sarah

2024-02-28 15:19 UTC, sedavid01 commented on R/tcplhit2_core.R
> +    warning("'errfun' is missing in the output from tcplfit2_core. 'errfun' tracks the error distribution assumed for the model fits and should be provided in 'params' list.")
Suggest just adding "-- see tcplfit2_core help for additional details." at the end of the error function.

2024-02-28 15:52 UTC, sedavid01 approved these changes
Approving changes.  @brown-jason please review and merge to 'dev' (via squash and merge) when you approve of the updates.

2024-02-28 16:28 UTC, cthunes commented
It may be useful to either change `warning()` to `error()` to abort before running into another error, or to throw `warning()` and also set `errfun` to default `"dt4"` `errfun <- "dt4"`. What do guys you think?

2024-02-28 16:43 UTC, sedavid01 commented
> It may be useful to either change `warning()` to `error()` to abort before running into another error, or to throw `warning()` and also set `errfun` to default `"dt4"` `errfun <- "dt4"`. What do you guys think?

Ahhh, good catch.  Yes, this should throw an error rather than a warning.

2024-02-28 16:43 UTC, sedavid01 requested changes

2024-02-28 16:43 UTC, sedavid01 commented on R/tcplhit2_core.R
> +    warning("'errfun' is missing in the output from tcplfit2_core. 'errfun' tracks the error distribution assumed for the model fits and should be provided in 'params' list. -- see tcplfit2_core help
change to 'stop' rather than 'warning'

2024-02-28 16:51 UTC, sedavid01 approved these changes
Re-approving changes.

2024-03-04 18:03 UTC, cthunes approved these changes

2024-03-04 18:05 UTC, cthunes commented
It threw an appropriate error when I didn't include the necessary parameter and when I did, I was able to process successfully. Thanks!

2024-03-04 19:04 UTC, merged